### ISSUE TITLE
Error with nanocompore sampcomp

### ISSUE THREAD

**Issue by Huanle** [tleonardi/nanocompore#112]
Hi @tleonardi ,

I ran into an error with this command:

```
nanocompore sampcomp --file_list1 bc1.evnaln.collapse/out_eventalign_collapse.tsv,bc2.evnaln.collapse/out_eventalign_collapse.tsv,bc3.evnaln.collapse/out_eventalign_collapse.tsv --file_list2 bc4.evnaln.collapse/out_eventalign_collapse.tsv --label1 KO --label2 WT --fasta yeast_rRNA_ref.fa --outpath ./results --overwrite --nthreads 8
error message:
Initialising SampComp and checking options
Only 1 replicate found for condition WT
This is not recommended. The statistics will be calculated with the logit method
Initialising Whitelist and checking options
Reading eventalign index files
References found in index: 4
Filtering out references with low coverage
References remaining after reference coverage filtering: 2
Starting data processing
M 0%| | 0/2 [00:00<?, ? Processed References/s]M 0%| | 0/2 [00:00<?, ? Processed References/s]
Loading SampCompDB
Traceback (most recent call last):
File "/nfs/users2/enovoa/hliu/mygit/nanocompare/bin/nanocompore", line 8, in 
sys.exit(main())
File "/nfs/users2/enovoa/hliu/mygit/nanocompare/lib/python3.6/site-packages/nanocompore/main.py", line 139, in main
args.func(args)
File "/nfs/users2/enovoa/hliu/mygit/nanocompare/lib/python3.6/site-packages/nanocompore/main.py", line 174, in sampcomp_main
db = s()
File "/nfs/users2/enovoa/hliu/mygit/nanocompare/lib/python3.6/site-packages/nanocompore/SampComp.py", line 268, in call
log_level=self.__log_level)
File "/nfs/users2/enovoa/hliu/mygit/nanocompare/lib/python3.6/site-packages/nanocompore/SampCompDB.py", line 82, in init
raise NanocomporeError("The result database is empty")
nanocompore.common.NanocomporeError: The result database is empty
Initialising SampComp and checking options
Only 1 replicate found for condition WT
This is not recommended. The statistics will be calculated with the logit method
Initialising Whitelist and checking options
Reading eventalign index files
References found in index: 4
Filtering out references with low coverage
References remaining after reference coverage filtering: 2
Starting data processing
M 0%| | 0/2 [00:00<?, ? Processed References/s]M 0%| | 0/2 [00:00<?, ? Processed References/s]
Loading SampCompDB
Traceback (most recent call last):
File "/nfs/users2/enovoa/hliu/mygit/nanocompare/bin/nanocompore", line 8, in 
sys.exit(main())
File "/nfs/users2/enovoa/hliu/mygit/nanocompare/lib/python3.6/site-packages/nanocompore/main.py", line 139, in main
args.func(args)
File "/nfs/users2/enovoa/hliu/mygit/nanocompare/lib/python3.6/site-packages/nanocompore/main.py", line 174, in sampcomp_main
db = s()
File "/nfs/users2/enovoa/hliu/mygit/nanocompare/lib/python3.6/site-packages/nanocompore/SampComp.py", line 268, in call
log_level=self.__log_level)
File "/nfs/users2/enovoa/hliu/mygit/nanocompare/lib/python3.6/site-packages/nanocompore/SampCompDB.py", line 82, in init
raise NanocomporeError("The result database is empty")
nanocompore.common.NanocomporeError: The result database is empty
```

Can you help to fix it? Thanks a lot!

**Comment by tleonardi** [comment]
Hi @Huanle,
the error `NanocomporeError: The result database is empty` is due to the fact that there are no significant positions in any transcripts.
Your reference contains 4 transcript, of which only 2 pass the coverage threshold (the threshold can be changed with `--min_coverage`). It's possible that neither of these is modified. But it's also possible that you don't have enough statistical power to detect modification, since you are not providing replicates for the WT condition.
Lastly, I would imagine the read number is very unbalanced between the two conditions (you have three KO samples vs 1 WT sample): this is not advised, as it might cause issues when fitting the GMM (however it shouldn't affect too much the other statistical tests).

If you were willing to share your eventalign_collapse files I'd be happy to better look into the problem!

**Comment by tleonardi** [comment]
closing for now, but happy to reopen if you think there's an issue!
