### ISSUE TITLE
Installing problem of nanocompore 

### ISSUE THREAD

**Issue by aman21392** [tleonardi/nanocompore#142]
I don't know what is the problem during downloading and after executing nanocompore command. I tried all way which you tell https://nanocompore.rna.rocks/installation/ . but when i doing help command i didn't get anything but error-
~$ nanocompore sampcomp --help
Traceback (most recent call last):
  File "/home/aclab/.local/bin/nanocompore", line 7, in <module>
    from nanocompore.__main__ import main
  File "/home/aclab/.local/lib/python3.6/site-packages/nanocompore/__main__.py", line 15, in <module>
    from nanocompore.SampComp import SampComp
  File "/home/aclab/.local/lib/python3.6/site-packages/nanocompore/SampComp.py", line 23, in <module>
    from nanocompore.TxComp import txCompare
  File "/home/aclab/.local/lib/python3.6/site-packages/nanocompore/TxComp.py", line 12, in <module>
    import statsmodels.discrete.discrete_model as dm
  File "/home/aclab/.local/lib/python3.6/site-packages/statsmodels/__init__.py", line 10, in <module>
    from statsmodels.tools.sm_exceptions import (ConvergenceWarning, CacheWriteWarning,
  File "/home/aclab/.local/lib/python3.6/site-packages/statsmodels/tools/__init__.py", line 1, in <module>
    from .tools import add_constant, categorical
  File "/home/aclab/.local/lib/python3.6/site-packages/statsmodels/tools/tools.py", line 9, in <module>
    import pandas as pd
  File "/home/aclab/.local/lib/python3.6/site-packages/pandas/__init__.py", line 42, in <module>
    from pandas.core.api import *
  File "/home/aclab/.local/lib/python3.6/site-packages/pandas/core/api.py", line 7, in <module>
    from pandas.core.arrays.integer import (
  File "/home/aclab/.local/lib/python3.6/site-packages/pandas/core/arrays/__init__.py", line 2, in <module>
    from .base import (ExtensionArray,    # noqa
  File "/home/aclab/.local/lib/python3.6/site-packages/pandas/core/arrays/base.py", line 21, in <module>
    from pandas.core import ops
  File "/home/aclab/.local/lib/python3.6/site-packages/pandas/core/ops/__init__.py", line 43, in <module>
    from pandas.core.ops.mask_ops import kleene_and, kleene_or, kleene_xor  # noqa: F401
  File "/home/aclab/.local/lib/python3.6/site-packages/pandas/core/ops/mask_ops.py", line 120, in <module>
    left: Union[bool, libmissing.NAType, np.ndarray],
AttributeError: module 'pandas._libs.missing' has no attribute 'NAType'

So please help me to get this problem to solve as soon as possible. I do all other steps which are required for this command. So i want please solve this issue first time i got stuck into not installing  program.
Thank you  in advance

**Comment by a-slide** [comment]
Hi @aman21392,

Looking at the log, I suppose there is a library conflict with things you have previously installed.

Would you be able to create a clean virtual environment with conda or virtualenv (as recommanded in the installation instructions) and try again ?

**Comment by Hemantr05** [comment]
@aman21392 I had the same issue. 
I was able to fix it by downgrading the pandas version to 0.24.0

Basically, `pip install pandas==0.24.0`
