### ISSUE TITLE
nanocompore sampcomp - Reading eventalign index files - References found in index: 0

### ISSUE THREAD

**Issue by ADelgadoT** [tleonardi/nanocompore#152]
Hi, 

I'm trying to run nanocompore on a set of samples using this command: 
`nanocompore sampcomp --nthreads 8    --file_list1 sample_1/out_eventalign_collapse.tsv     --file_list2 sample_2/out_eventalign_collapse.tsv     --label1 sample_1     --label2 sample_2    --fasta rRNA_Maternal.fa     --outpath ./sample_1--sample_2_nanocompres/     --sequence_context 4 --downsample_high_coverage 10000 --pvalue_thr 1 --logit --comparison_methods GMM,KS,MW,TT --overwrite`

When running it, I get the following error: 
```
Initialising SampComp and checking options
Only 1 replicate found for condition CK-43-TOT-WT2
This is not recommended. The statistics will be calculated with the logit method
Only 1 replicate found for condition CK-44-TOT-WT4
This is not recommended. The statistics will be calculated with the logit method
Initialising Whitelist and checking options
Reading eventalign index files
	References found in index: 0
Filtering out references with low coverage
	References remaining after reference coverage filtering: 0
Starting data processing
0 Processed References [00:00, ? Processed References/s]
Loading SampCompDB
Traceback (most recent call last):
  File "/usr/local/python/versions/3.6.3/bin/nanocompore", line 8, in <module>
    sys.exit(main())
  File "/usr/local/python/versions/3.6.3/lib/python3.6/site-packages/nanocompore/__main__.py", line 139, in main
    args.func(args)
  File "/usr/local/python/versions/3.6.3/lib/python3.6/site-packages/nanocompore/__main__.py", line 174, in sampcomp_main
    db = s()
  File "/usr/local/python/versions/3.6.3/lib/python3.6/site-packages/nanocompore/SampComp.py", line 268, in __call__
    log_level=self.__log_level)
  File "/usr/local/python/versions/3.6.3/lib/python3.6/site-packages/nanocompore/SampCompDB.py", line 82, in __init__
    raise NanocomporeError("The result database is empty")
nanocompore.common.NanocomporeError: The result database is empty
```

Do you have any idea about how to solve it? I've been looking through your documentation and I could not fix it.

Thanks in advance for the help!

**Comment by tleonardi** [comment]
Hi @ADelgadoT,
the issue is explained in these line:
```
Reading eventalign index files
	References found in index: 0
Filtering out references with low coverage
	References remaining after reference coverage filtering: 0
```
For some reasons it looks like your input is actually empty.
Could you check the output file of NanopolishComp? What do they contain?
